TestingKnowledge.Web/Controllers/AccountsController.cs
using System;
using System.Collections.Generic;

using Microsoft.AspNetCore.Mvc;
using Microsoft.Practices.Unity;

using TestingKnowledge.Dto;
using TestingKnowledge.Service;
using TestingKnowledge.Web.Models;
using TestingKnowledge.Web.Utils;

namespace TestingKnowledge.Web.Controllers
{
    public class AccountsController : BasicController
    {
        public IActionResult Index()
        {
            IActionResult result = AcceptOrRedirect( AccountRole.Admin );
            if ( result != null )
                return result;

            AccountsModel model = new AccountsModel();
            model.AuthAccount = GetAccount();
            model.Accounts = LoadAccounts();
            return View( model  );
        }

        private IList< AccountSecureDto > LoadAccounts()
        {
            List< AccountSecureDto > accounts = new List< AccountSecureDto >();
            foreach ( Guid accountId in accountService.ViewAll() )
                accounts.Add( accountService.View( accountId ) );
            return accounts;
        }

        [HttpPost]
        public IActionResult View( Guid accountId )
        {
            IActionResult result = AcceptOrRedirect( AccountRole.Admin );
            if ( result != null )
                return null;

            return Json( accountService.View( accountId ) );
        }

        [HttpPost]
        public IActionResult CreateAccount( string login, string password, AccountRole role )
        {
            IActionResult result = AcceptOrRedirect( AccountRole.Admin );
            if ( result != null )
                return null;

            try
            {
                Guid accountId = accountService.Create( role, login, password );

                AccountModel model = new AccountModel();
                model.AuthAccount = GetAccount();
                model.Account = new AccountDto( accountId, login, password, role );
                return View( "Account", model );
            }
            catch ( Exception ex )
            {
                return Json( ex );
            }
        }

        [HttpPost]
        public IActionResult EditAccount( Guid accountId, string login, string password, AccountRole role )
        {
            IActionResult result = AcceptOrRedirect( AccountRole.Admin );
            if ( result != null )
                return null;
            
            try
            {
                AccountDto account = accountService.View( accountId );

                if (  account.Login != login )
                    accountService.EditLogin( accountId, login );
            
                if ( account.Password != password )
                    accountService.EditPassword( accountId, password );
            
                if ( account.Role != role )
                    accountService.EditRole( accountId, role );
            }
            catch( Exception ex )
            {
                return Json( ex.Message );
            }

            return Json( true );
        }

        [HttpPost]
        public void RemoveAccount( Guid accountId )
        {
            IActionResult result = AcceptOrRedirect( AccountRole.Admin );
            if ( result != null )
                return;

            accountService.Delete( accountId );
        }
    }
}

TestingKnowledge.Web/Controllers/TestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Practices.Unity;

using TestingKnowledge.Dto;
using TestingKnowledge.Service;
using TestingKnowledge.Web.Models;
using TestingKnowledge.Web.Utils;

namespace TestingKnowledge.Web.Controllers
{
    public class TestsController : BasicController
    {
        public IActionResult Index()
        {
            IActionResult result = AcceptOrRedirect( AccountRole.Admin | AccountRole.Moderator );
            if ( result != null )
                return result;

            TestsModel model = new TestsModel();
            model.AuthAccount = GetAccount();
            model.Tests = LoadAccountTests();
            return View( model );
        }

        private IList< TestDto > LoadAccountTests()
        {
            AccountDto account = GetAccount();
            if ( account == null )
                return new List< TestDto > ();

            var tests = testEditorService.ViewByCreator( account.DomainId ).ToArray();
            return tests.Select( testId => testEditorService.View( testId ) ).ToList();
        }

        [Dependency]
        protected ITestEditorService testEditorService { get; set; }
    }
}

TestingKnowledge.Web/Views/Shared/_BasicInternalLayout.cshtml
@using TestingKnowledge.Dto
@using Microsoft.AspNetCore.Localization
@using Microsoft.Extensions.Localization;
@model TestingKnowledge.Web.Models.BasicModel
@inject IStringLocalizer< TestingKnowledge.Web.Resources > Localizer
@{
    Layout = "_BasicLayout";

    var requestCulture = Context.Features.Get< IRequestCultureFeature >();
    var language = requestCulture.RequestCulture.Culture.TwoLetterISOLanguageName;

}
@section HeaderContent
{
    <script src="~/js/navbar.js"></script>

    @RenderSection( "HeaderContent", required: false )
}
<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li @if ( ViewBag.ActiveLink == "home" ) { @: class="active"
                                            }>
                    <a href="@Url.Action( "Index", "Home" )">@Localizer[ "Home" ]</a>
                </li>
                @if ( Model.AuthAccount.Role == AccountRole.Admin )
                {
                    <li @if ( ViewBag.ActiveLink == "accounts" ) { @: class="active"
                                                                            }>
                        <a href="@Url.Action( "Index", "Accounts" )">@Localizer[ "Accounts" ]</a>
                    </li>
                }
                @if ( @Model.AuthAccount.Role != AccountRole.User )
                {
                    <li @if ( ViewBag.ActiveLink == "tests" ) {
                            @: class="active"
                        }>
                        <a href="@Url.Action( "Index", "Tests" )">@Localizer[ "Tests" ]</a>
                    </li>
                }
            </ul>
            <div class="navbar-right">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"><span class="lang-sm lang-lbl-full" lang="@language"></span> <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><button type="button" class="btn btn-link" onclick="setLocale('en');"><span class="lang-sm lang-lbl-full" lang="en"></span></button></li>
                            <li><button type="button" class="btn btn-link" onclick="setLocale('ru');"><span class="lang-sm lang-lbl-full" lang="ru"></span></button></li>
                            <li><button type="button" class="btn btn-link" onclick="setLocale('uk');"><span class="lang-sm lang-lbl-full" lang="uk"></span></button></li>
                        </ul>
                    </li>
                    <li><a href="javascript:onExit()">@Localizer[ "Exit" ]</a></li>
                </ul>
            </div>
        </div>
    </div>
</nav>
@RenderBody()

TestingKnowledge.Web/Views/Shared/_BasicLayout.cshtml
@using Microsoft.AspNetCore.Localization
@using Microsoft.Extensions.Localization;

@inject IStringLocalizer< TestingKnowledge.Web.Resources > Localizer

@{
    var requestCulture = Context.Features.Get< IRequestCultureFeature >();
    var language = requestCulture.RequestCulture.Culture.TwoLetterISOLanguageName;
}
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>@ViewBag.Title</title>

    <link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/lib/bootstrapValidator/dist/css/bootstrapValidator.min.css" />
    <link rel="stylesheet" href="/lib/languages/languages.min.css" />

    <link rel="stylesheet" href="/css/main.css" />
    
    <script src="/lib/jquery/dist/jquery.min.js"></script>
    <script src="/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="/lib/bootstrapValidator/dist/js/bootstrapValidator.min.js"></script>
    <script src="/lib/ztoast/ztoast.min.js"></script>

    <script src="~/js/set_locale.js"></script>

    @RenderSection( "HeaderContent", required: false )

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->


</head>
    <body>
        @RenderBody()
    </body>
</html>